### ISSUE TITLE
Update "The Tao of Project Management" and bio for revised third edition

### ISSUE THREAD

**Issue by amatlack** [open-organization/open-org-leaders-manual#49]
We need to review/revise/update articles in preparation for the revised Third Edition of the Open Org Leaders Manual.

- [x] Update [the article](https://github.com/open-organization/open-org-leaders-manual/blob/master/22-matlack-tao-project-management.md)
- [x] Update [personal bio](https://github.com/open-organization/open-org-leaders-manual/blob/master/27-contributors.md) (for #45 )

**Comment by amatlack** [comment]
I keep reading [this](https://github.com/open-organization/open-org-leaders-manual/blob/master/22-matlack-tao-project-management.md), @semioticrobotic , and all I keep thinking is "ooh it's baby allison", but the content is still relevant, and I don't know what I would change to improve it. Maybe we could add an "editor's note" at the top saying this is baby allison, but she still approves this message?? 😆 

@LauraHilliger what say you? 👀

**Comment by LauraHilliger** [comment]
I don't think you need to change anything here, with an exception of editing the "Last fall, I enrolled..." to be "I once enrolled in a..." This article stands the test of time. Also, "baby allison" may have had on brand new rose colored glasses, but I know you and even with all the scratches, you're still a believer. If you weren't, we wouldn't be here ;)

**Comment by LauraHilliger** [comment]
Perhaps add "Although originally written more than 5 years ago, upon revision for this third edition of the Open Organization's Leader Manual, the author and the community decided that only superficial edits were necessary."

**Comment by amatlack** [comment]
@LauraHilliger it was from [2016](https://opensource.com/open-organization/16/2/tao-project-management), so we're nearing a decade now!! 🙈  It was the first article I ever had published with the open org. @semioticrobotic found me on the intranet 😆
