### ISSUE TITLE
Update Visualizing your plans and progress

### ISSUE THREAD

**Issue by jimmysjolund** [open-organization/open-org-leaders-manual#50]
Either update and add new ideas and experiences or write a separate chapter. What do you think @semioticrobotic ? I have a more recent example using the Open Decision Framework and a bit more experience using A3 reports. Then Spotify Rhythm and the Servant Door is now a bit old (and probably not relevant in Spotify either).

**Comment by jimmysjolund** [comment]
Could also do a part on Obeya practice and Obeya rooms.

**Comment by semioticrobotic** [comment]
Liking the new additions, @jimmysjolund! I made a few editorial changes and left some comments for you. [See what you think](https://hackmd.io/2wlhPgL4T7WaMQzYX4XxGQ). Very glad you're updating this one!

**Comment by semioticrobotic** [comment]
Working on this a bit more today, @jimmysjolund, in an effort to respond to your comments on my comments about your comments.

**Comment by semioticrobotic** [comment]
This is good to go from my perspective, @jimmysjolund. Nice work! If you want to open the related pull request, feel free to assign me as reviewer since I'm already familiar with what you've got going on here.

**Comment by jimmysjolund** [comment]
PR https://github.com/open-organization/open-org-leaders-manual/pull/62
